package Pojos;
// Generated Jul 7, 2015 3:15:46 AM by Hibernate Tools 3.6.0



/**
 * Catproveedor generated by hbm2java
 */
public class Catproveedor  implements java.io.Serializable {


     private Integer numeroProveedores;
     private String rfcProveedores;
     private String nombreProveedores;
     private String nombreDistribuidora;
     private int telefono;
     private String correoProveedor;
     private String categoriaIdCategoria;
//     private int console;

    public Catproveedor() {
    }

    public Catproveedor(String rfcProveedores, String nombreProveedores, String nombreDistribuidora, int telefono, String correoProveedor, String categoriaIdCategoria) {
       this.rfcProveedores = rfcProveedores;
       this.nombreProveedores = nombreProveedores;
       this.nombreDistribuidora = nombreDistribuidora;
       this.telefono = telefono;
       this.correoProveedor = correoProveedor;
       this.categoriaIdCategoria = categoriaIdCategoria;
//       this.console= console;
    }
   
    public Integer getNumeroProveedores() {
        return this.numeroProveedores;
    }
    
    public void setNumeroProveedores(Integer numeroProveedores) {
        this.numeroProveedores = numeroProveedores;
    }
    public String getRfcProveedores() {
        return this.rfcProveedores;
    }
    
    public void setRfcProveedores(String rfcProveedores) {
        this.rfcProveedores = rfcProveedores;
    }
    public String getNombreProveedores() {
        return this.nombreProveedores;
    }
    
    public void setNombreProveedores(String nombreProveedores) {
        this.nombreProveedores = nombreProveedores;
    }
    public String getNombreDistribuidora() {
        return this.nombreDistribuidora;
    }
    
    public void setNombreDistribuidora(String nombreDistribuidora) {
        this.nombreDistribuidora = nombreDistribuidora;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreoProveedor() {
        return this.correoProveedor;
    }
    
    public void setCorreoProveedor(String correoProveedor) {
        this.correoProveedor = correoProveedor;
    }
    public String getCategoriaIdCategoria() {
        return this.categoriaIdCategoria;
    }
    
    public void setCategoriaIdCategoria(String categoriaIdCategoria) {
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
//    public int getConsole() {
//        return console;
//    }
// 
//    public void setConsole(int console) {
//        this.console = console;
//    }




}


