package Pojos;
// Generated Jul 7, 2015 3:15:46 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catproducto generated by hbm2java
 */
public class Catproducto implements java.io.Serializable {

    private Integer idProducto;
    private int numeroCodigo;
    private String nombreProducto;
    private Date fechaRegistroProducto;
    private String descripcionProducto;
    private int categoriaIdCategoria;
    private int catProveedorNumeroProveedores;
    private BigDecimal precioVentaUnitario;
    private int cantidad;
    private int cantidadMin;
    private int cantidadMax;
    private Set ventadetalles = new HashSet(0);

    public Catproducto() {
    }

    public Catproducto(int numeroCodigo, String nombreProducto, Date fechaRegistroProducto, String descripcionProducto, int categoriaIdCategoria, int catProveedorNumeroProveedores, BigDecimal precioVentaUnitario, int cantidad, int cantidadMin, int cantidadMax) {
        this.numeroCodigo = numeroCodigo;
        this.nombreProducto = nombreProducto;
        this.fechaRegistroProducto = fechaRegistroProducto;
        this.descripcionProducto = descripcionProducto;
        this.categoriaIdCategoria = categoriaIdCategoria;
        this.catProveedorNumeroProveedores = catProveedorNumeroProveedores;
        this.precioVentaUnitario = precioVentaUnitario;
        this.cantidad = cantidad;
        this.cantidadMin = cantidadMin;
        this.cantidadMax = cantidadMax;
    }

    public Catproducto(int numeroCodigo, String nombreProducto, Date fechaRegistroProducto, String descripcionProducto, int categoriaIdCategoria, int catProveedorNumeroProveedores, BigDecimal precioVentaUnitario, int cantidad, int cantidadMin, int cantidadMax, Set ventadetalles) {
        this.numeroCodigo = numeroCodigo;
        this.nombreProducto = nombreProducto;
        this.fechaRegistroProducto = fechaRegistroProducto;
        this.descripcionProducto = descripcionProducto;
        this.categoriaIdCategoria = categoriaIdCategoria;
        this.catProveedorNumeroProveedores = catProveedorNumeroProveedores;
        this.precioVentaUnitario = precioVentaUnitario;
        this.cantidad = cantidad;
        this.cantidadMin = cantidadMin;
        this.cantidadMax = cantidadMax;
        this.ventadetalles = ventadetalles;
    }

    public Integer getIdProducto() {
        return this.idProducto;
    }

    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    public int getNumeroCodigo() {
        return this.numeroCodigo;
    }

    public void setNumeroCodigo(int numeroCodigo) {
        this.numeroCodigo = numeroCodigo;
    }

    public String getNombreProducto() {
        return this.nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    public Date getFechaRegistroProducto() {
        return this.fechaRegistroProducto;
    }

    public void setFechaRegistroProducto(Date fechaRegistroProducto) {
        this.fechaRegistroProducto = fechaRegistroProducto;
    }

    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }

    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }

    public int getCategoriaIdCategoria() {
        return this.categoriaIdCategoria;
    }

    public void setCategoriaIdCategoria(int categoriaIdCategoria) {
        this.categoriaIdCategoria = categoriaIdCategoria;
    }

    public int getCatProveedorNumeroProveedores() {
        return this.catProveedorNumeroProveedores;
    }

    public void setCatProveedorNumeroProveedores(int catProveedorNumeroProveedores) {
        this.catProveedorNumeroProveedores = catProveedorNumeroProveedores;
    }

    public BigDecimal getPrecioVentaUnitario() {
        return this.precioVentaUnitario;
    }

    public void setPrecioVentaUnitario(BigDecimal precioVentaUnitario) {
        this.precioVentaUnitario = precioVentaUnitario;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Set getVentadetalles() {
        return this.ventadetalles;
    }

    public void setVentadetalles(Set ventadetalles) {
        this.ventadetalles = ventadetalles;
    }

    public int getCantidadMin() {
        return this.cantidadMin;
    }

    public void setCantidadMin(int cantidadMin) {
        this.cantidadMin = cantidadMin;
    }

    public int getCantidadMax() {
        return this.cantidadMax;
    }

    public void setCantidadMax(int cantidadMax) {
        this.cantidadMax = cantidadMax;
    }

}
