package Pojos;
// Generated Jul 7, 2015 3:15:46 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer numeroPedido;
     private Date fechaPedido;
     private int cantidadRequerida;
     private float precioAprox;
     private int usuariosIdUsuarios;
     private int categoriaIdCategoria;
     private int catProveedorNumeroProveedores;
     private int catProductoIdProducto;

    public Pedido() {
    }

    public Pedido(Date fechaPedido, int cantidadRequerida, float precioAprox, int usuariosIdUsuarios, int categoriaIdCategoria, int catProveedorNumeroProveedores, int catProductoIdProducto) {
       this.fechaPedido = fechaPedido;
       this.cantidadRequerida = cantidadRequerida;
       this.precioAprox = precioAprox;
       this.usuariosIdUsuarios = usuariosIdUsuarios;
       this.categoriaIdCategoria = categoriaIdCategoria;
       this.catProveedorNumeroProveedores = catProveedorNumeroProveedores;
       this.catProductoIdProducto = catProductoIdProducto;
    }
   
    public Integer getNumeroPedido() {
        return this.numeroPedido;
    }
    
    public void setNumeroPedido(Integer numeroPedido) {
        this.numeroPedido = numeroPedido;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public int getCantidadRequerida() {
        return this.cantidadRequerida;
    }
    
    public void setCantidadRequerida(int cantidadRequerida) {
        this.cantidadRequerida = cantidadRequerida;
    }
    public float getPrecioAprox() {
        return this.precioAprox;
    }
    
    public void setPrecioAprox(float precioAprox) {
        this.precioAprox = precioAprox;
    }
    public int getUsuariosIdUsuarios() {
        return this.usuariosIdUsuarios;
    }
    
    public void setUsuariosIdUsuarios(int usuariosIdUsuarios) {
        this.usuariosIdUsuarios = usuariosIdUsuarios;
    }
    public int getCategoriaIdCategoria() {
        return this.categoriaIdCategoria;
    }
    
    public void setCategoriaIdCategoria(int categoriaIdCategoria) {
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
    public int getCatProveedorNumeroProveedores() {
        return this.catProveedorNumeroProveedores;
    }
    
    public void setCatProveedorNumeroProveedores(int catProveedorNumeroProveedores) {
        this.catProveedorNumeroProveedores = catProveedorNumeroProveedores;
    }
    public int getCatProductoIdProducto() {
        return this.catProductoIdProducto;
    }
    
    public void setCatProductoIdProducto(int catProductoIdProducto) {
        this.catProductoIdProducto = catProductoIdProducto;
    }




}


