package Pojos;
// Generated Jul 7, 2015 3:15:46 AM by Hibernate Tools 3.6.0



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private String nombre;
     private String apPaterno;
     private String apMaterno;
     private int telefono;
     private String nombreUsuario;
     private String contrasena;
     private int tipoUsuarioIdTipoUsuario;

    public Usuarios() {
    }

    public Usuarios(String nombre, String apPaterno, String apMaterno, int telefono, String nombreUsuario, String contrasena, int tipoUsuarioIdTipoUsuario) {
       this.nombre = nombre;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.telefono = telefono;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.tipoUsuarioIdTipoUsuario = tipoUsuarioIdTipoUsuario;
    }
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public int getTipoUsuarioIdTipoUsuario() {
        return this.tipoUsuarioIdTipoUsuario;
    }
    
    public void setTipoUsuarioIdTipoUsuario(int tipoUsuarioIdTipoUsuario) {
        this.tipoUsuarioIdTipoUsuario = tipoUsuarioIdTipoUsuario;
    }




}


