package Pojos;
// Generated Jul 7, 2015 3:15:46 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer numeroVenta;
     private BigDecimal precioVentaTotal;
     private Date fechaVenta;
     private Set ventadetalles = new HashSet(0);

    public Venta() {
    }

	
    public Venta(BigDecimal precioVentaTotal, Date fechaVenta) {
        this.precioVentaTotal = precioVentaTotal;
        this.fechaVenta = fechaVenta;
    }
    public Venta(BigDecimal precioVentaTotal, Date fechaVenta, Set ventadetalles) {
       this.precioVentaTotal = precioVentaTotal;
       this.fechaVenta = fechaVenta;
       this.ventadetalles = ventadetalles;
    }
   
    public Integer getNumeroVenta() {
        return this.numeroVenta;
    }
    
    public void setNumeroVenta(Integer numeroVenta) {
        this.numeroVenta = numeroVenta;
    }
    public BigDecimal getPrecioVentaTotal() {
        return this.precioVentaTotal;
    }
    
    public void setPrecioVentaTotal(BigDecimal precioVentaTotal) {
        this.precioVentaTotal = precioVentaTotal;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Set getVentadetalles() {
        return this.ventadetalles;
    }
    
    public void setVentadetalles(Set ventadetalles) {
        this.ventadetalles = ventadetalles;
    }




}


